//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakeBusDraft {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TakeBusDraft.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получить информацию о сервисе .
        /// </summary>
        internal static string _aboutDialogCommand {
            get {
                return ResourceManager.GetString("_aboutDialogCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завершить.
        /// </summary>
        internal static string _cancelDialogCommand {
            get {
                return ResourceManager.GetString("_cancelDialogCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стоимость билета.
        /// </summary>
        internal static string _commonDialogCommand {
            get {
                return ResourceManager.GetString("_commonDialogCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сall-центр.
        /// </summary>
        internal static string _supportDialogCommand {
            get {
                return ResourceManager.GetString("_supportDialogCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to К сожалению мне не удалось вас понять. Пожалуйста повторите запрос или позвоните нам по телефону: +7 (495) 642-35-04.
        /// </summary>
        internal static string AnswerNotFound {
            get {
                return ResourceManager.GetString("AnswerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оплатить .
        /// </summary>
        internal static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтобы оплатить билет, пожалуйста войдите в личный кабинет: https://www.takebus.ru/auth/login.
        /// </summary>
        internal static string BuyReply {
            get {
                return ResourceManager.GetString("BuyReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для связи с call-центром, пожалуйста, позвоните нам по телефону: x-xxx-xxx.
        /// </summary>
        internal static string CallCenter {
            get {
                return ResourceManager.GetString("CallCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to руб..
        /// </summary>
        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Какая дата?.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата поездки:.
        /// </summary>
        internal static string DateField {
            get {
                return ResourceManager.GetString("DateField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to До свидания, обращайтесь еще!.
        /// </summary>
        internal static string EndMessage {
            get {
                return ResourceManager.GetString("EndMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мы смогли ответить на ваш вопрос?.
        /// </summary>
        internal static string FeedbackQuesion {
            get {
                return ResourceManager.GetString("FeedbackQuesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спасибо за ваш отзыв!.
        /// </summary>
        internal static string FeedbackThanksMessage {
            get {
                return ResourceManager.GetString("FeedbackThanksMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отлично! Из какого города вы хотите выехать?.
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Город отправления:.
        /// </summary>
        internal static string FromField {
            get {
                return ResourceManager.GetString("FromField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чем еще я могу вам помочь?.
        /// </summary>
        internal static string HelpMessage {
            get {
                return ResourceManager.GetString("HelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я бот-помощник сервиса TakeBus!.
        /// </summary>
        internal static string IntroMessage {
            get {
                return ResourceManager.GetString("IntroMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не нашли подходящий ответ?.
        /// </summary>
        internal static string NoAnswerCard {
            get {
                return ResourceManager.GetString("NoAnswerCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очень сожалеем! Позвоните нам по телефону x-xxx-xxx.
        /// </summary>
        internal static string NoAnswerCardMessage {
            get {
                return ResourceManager.GetString("NoAnswerCardMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Еще подходящий вариант.
        /// </summary>
        internal static string PossibleAnswerCard {
            get {
                return ResourceManager.GetString("PossibleAnswerCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спасибо за использование нашего сервиса!.
        /// </summary>
        internal static string SaveReply {
            get {
                return ResourceManager.GetString("SaveReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спасибо! Обращайтесь еще..
        /// </summary>
        internal static string ThankYouMessage {
            get {
                return ResourceManager.GetString("ThankYouMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш билет.
        /// </summary>
        internal static string TicketTitle {
            get {
                return ResourceManager.GetString("TicketTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В какое время?.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время отправления:.
        /// </summary>
        internal static string TimeField {
            get {
                return ResourceManager.GetString("TimeField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to А в какой город направляетесь?.
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Город прибытия:.
        /// </summary>
        internal static string ToField {
            get {
                return ResourceManager.GetString("ToField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите одну из опций или напишите мне свой вопрос:.
        /// </summary>
        internal static string TryOptions {
            get {
                return ResourceManager.GetString("TryOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добрый день!.
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2017 г..
        /// </summary>
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
