//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakeBusDraft {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TakeBusDraft.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получить информацию о сервисе .
        /// </summary>
        internal static string _aboutDialogCommand {
            get {
                return ResourceManager.GetString("_aboutDialogCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завершить беседу.
        /// </summary>
        internal static string _cancelDialogCommand {
            get {
                return ResourceManager.GetString("_cancelDialogCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Узнать чем я могу помочь.
        /// </summary>
        internal static string _commonDialogCommand {
            get {
                return ResourceManager.GetString("_commonDialogCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Связаться с call-центром.
        /// </summary>
        internal static string _supportDialogCommand {
            get {
                return ResourceManager.GetString("_supportDialogCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to К сожалению мне не удалось вас понять. Пожалуйста повторите запрос или позвоните нам по телефону: +7 (495) 642-35-04.
        /// </summary>
        internal static string AnswerNotFound {
            get {
                return ResourceManager.GetString("AnswerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to До свидания, обращайтесь еще!.
        /// </summary>
        internal static string EndMessage {
            get {
                return ResourceManager.GetString("EndMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я бот-помощник сервиса TakeBus!.
        /// </summary>
        internal static string IntroMessage {
            get {
                return ResourceManager.GetString("IntroMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите одну из опций или напишите мне свой вопрос:.
        /// </summary>
        internal static string MenuSubtitle {
            get {
                return ResourceManager.GetString("MenuSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чем еще я могу вам помочь?.
        /// </summary>
        internal static string MenuTitle {
            get {
                return ResourceManager.GetString("MenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добрый день!.
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
    }
}
